import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {Button} from './components/ui/button';
import {Badge} from './components/ui/badge';
import {Card,CardContent} from './components/ui/card';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from './components/ui/table';
import {Tabs,TabsList,TabsTrigger} from './components/ui/tabs';
import {Input} from './components/ui/input';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator} from './components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './components/ui/dialog';
import {MoreHorizontal,Plus,Search,ArrowUpDown,ExternalLink,Download,Upload,ChevronDown} from 'lucide-react';
const roots=new WeakMap<Element,any>();
function mount(el:Element,node:React.ReactNode){let r=roots.get(el);if(!r){r=createRoot(el);roots.set(el,r);}flushSync(()=>r.render(node));}
function action(name:string,id?:string){setTimeout(()=>{const b=document.createElement('button');b.dataset.action=name;if(id)b.dataset.id=id;b.hidden=true;document.body.append(b);b.click();b.remove();},0);}
function sourceURL(url:string){try{const u=new URL(url);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function Status({value,raw}:{value:string,raw?:string}){return <Badge variant="outline" className={'status-badge status-'+value}>{value==='面试中'?'面试':value}{raw&&raw!==value?' · '+raw:''}</Badge>}
function More({record,company=false}:any){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={record.company+' 更多操作'}><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="offer-menu"><DropdownMenuItem onSelect={()=>action(company?'company-edit':'edit',record.id)}>编辑{company?'公司':'岗位'}</DropdownMenuItem>{!company&&<DropdownMenuItem onSelect={()=>action('review',record.id)}>评价与复盘</DropdownMenuItem>}<DropdownMenuSeparator/><DropdownMenuItem className="text-red-600" onSelect={()=>action(company?'company-delete':'delete',record.id)}>{company?'移除计划':'删除岗位'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
function Identity({name,children}:any){return <div className="row-identity"><span className="row-avatar" aria-hidden="true">{name.slice(0,1)}</span><div><h3>{name}</h3>{children}</div></div>}
function OfficialLink({url}:any){const href=sourceURL(url);return href?<a className="row-official" href={href} target="_blank" rel="noopener noreferrer"><ExternalLink size={13}/>官网</a>:null;}
function StatusControl({j}:any){const [busy,setBusy]=useState(false);const options=(window as any).ApplicationCore.statusActions(j);if(!options.length)return null;const run=async(status:string)=>{if(busy)return;setBusy(true);try{await (window as any).EasyOfferStatusUpdate(j.id,status);}finally{setBusy(false);}};return <div className="status-control"><Button variant="secondary" disabled={busy} onClick={()=>run(options[0].status)}>{busy?'更新中…':options[0].label}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="secondary" disabled={busy} size="icon" aria-label={j.company+' 更新状态'}><ChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{options.map((o:any)=><DropdownMenuItem key={o.status} onSelect={()=>run(o.status)}>{o.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>}
function JobRow({j}:any){const info=(window as any).ApplicationCore.statusInfo(j);return <TableRow className="record-row"><TableCell><Identity name={j.company}><button className="row-role" onClick={()=>action('detail',j.id)}>{j.role}</button></Identity></TableCell><TableCell className="row-info"><div>{[j.location,j.category].filter(Boolean).join(' · ')||'—'}</div><OfficialLink url={j.url}/>{j.interview&&j.status==='面试中'?<span className="interview-note">面试 {j.interview.replace('T',' ')}</span>:j.deadline?<span>{j.deadline} 截止</span>:j.channel&&j.channel!=='官网'&&<span>{j.channel}</span>}</TableCell><TableCell className="row-status"><Status value={j.status} raw={j.rawStatus}/><div className="row-subtitle">{info.primary}</div>{info.secondary&&<div className="row-subtitle">{info.secondary}</div>}</TableCell><TableCell className="row-actions"><Button variant="outline" onClick={()=>action('detail',j.id)}>详情</Button><StatusControl j={j}/><More record={j}/></TableCell></TableRow>}
function PlanRow({g}:any){const [expanded,setExpanded]=useState(false);const base=g.records.find((r:any)=>r.kind==='company')||g.records[0];return <><TableRow className="record-row"><TableCell><Identity name={g.company}><span className="row-subtitle">{new Date(g.created).toLocaleDateString('zh-CN')} 添加{g.companyDeadline?' · '+g.companyDeadline+' 截止':''}</span></Identity></TableCell><TableCell className="row-info"><div>{[...new Set(g.records.map((r:any)=>r.channel).filter(Boolean))].join(' / ')||'—'}</div><OfficialLink url={base.url}/>{g.sizeValue>0&&<button className="row-subtitle" onClick={()=>action('company-size',base.id)}>{g.sizeLabel}</button>}{base.notes&&<span className="row-note" title={base.notes}>{base.notes}</span>}</TableCell><TableCell className="row-status">{g.jobRecords.length?<Button variant="ghost" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{g.jobRecords.length} 个岗位<ChevronDown className={expanded?'rotate-180':''}/></Button>:<span className="text-muted-foreground">待了解岗位</span>}</TableCell><TableCell className="row-actions"><Button variant="outline" onClick={()=>action('company-job',base.id)}><Plus/>添加岗位</Button><More company={base.kind==='company'} record={base}/></TableCell></TableRow>{expanded&&<TableRow><TableCell colSpan={4} className="expanded-jobs">{g.jobRecords.map((j:any)=><div key={j.id}><span>{j.role}</span><Button variant="ghost" onClick={()=>action('detail',j.id)}>查看详情</Button><Button variant="secondary" onClick={()=>action('advance',j.id)}>标记已投递</Button></div>)}</TableCell></TableRow>}</>}
function Rows({groups,list,showCompanies,pending}:any){return <div className="single-column">{showCompanies&&<section><div className="list-heading"><div><h2>计划投递 <span>{groups.length}</span></h2><p>已投递的公司会自动移出计划清单。</p></div><Button variant="outline" onClick={()=>action('company-add')}><Plus/>添加公司</Button></div><div className="table-surface"><Table><TableHeader><TableRow><TableHead>公司</TableHead><TableHead>渠道 / 备注</TableHead><TableHead>岗位</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{groups.length?groups.map((g:any)=><PlanRow key={g.key} g={g}/>):<TableRow><TableCell colSpan={4} className="empty-row">暂无匹配的计划公司</TableCell></TableRow>}</TableBody></Table></div></section>}{!pending&&<section>{showCompanies&&<div className="list-heading"><h2>岗位记录 <span>{list.length}</span></h2></div>}<div className="table-surface"><Table><TableHeader><TableRow><TableHead>公司 / 岗位</TableHead><TableHead>地点 / 部门</TableHead><TableHead>状态</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{list.length?list.map((j:any)=><JobRow key={j.id} j={j}/>):<TableRow><TableCell colSpan={4} className="empty-row">暂无匹配的岗位，试试其他筛选条件。</TableCell></TableRow>}</TableBody></Table></div></section>}</div>}
function Workspace(p:any){return <div className="shadcn-workspace"><div className="workspace-tools"><Tabs value={p.filter} onValueChange={p.onFilter}><TabsList className="filter-tabs">{p.filters.map(([key,label,count]:any)=><TabsTrigger key={key} value={key}>{label}<span className="filter-count">{count}</span></TabsTrigger>)}</TabsList></Tabs><div className="list-controls"><div className="search-control"><Search/><Input aria-label="搜索公司或岗位" placeholder="搜索公司或岗位…" value={p.query} onChange={e=>p.onQuery(e.target.value)}/></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><ArrowUpDown/>{p.sortLabel}</Button></DropdownMenuTrigger><DropdownMenuContent align="end">{p.sortOptions.map(([v,l]:any)=><DropdownMenuItem key={v} onSelect={()=>p.onSort(v)}>{l}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></div><div className="list-count">{p.count}</div><Rows {...p}/></div>}
function Stats({m}:any){return <div className="summary-grid">{[['计划投递',m.plannedCompanies,'家目标公司'],['已投递',m.submitted,'待后续进展'],['笔试 / 面试',m.written+m.interview,'个进行中岗位'],['Offer',m.offer,'份录用机会']].map(([label,n,note])=><Card key={label} className="summary-card"><CardContent><div>{label}</div><strong>{n}</strong><span>{note}</span></CardContent></Card>)}</div>}
function Navigation({tab,onChange}:any){return <Tabs value={tab} onValueChange={onChange}><TabsList className="main-tabs"><TabsTrigger value="jobs">投递清单</TabsTrigger><TabsTrigger value="schedule">面试日程</TabsTrigger><TabsTrigger value="analysis">数据分析</TabsTrigger></TabsList></Tabs>}
function Schedule({list}:any){return <section><div className="list-heading"><div><h2>面试日程</h2><p>{list.length} 场面试 · 按时间排列</p></div></div><Card><CardContent className="p-0">{list.length?list.map((j:any)=><div className="schedule-row" key={j.id}><div className="schedule-time">{j.interview.slice(0,10)}<span>{j.interview.slice(11)}</span></div><Identity name={j.company}><span className="row-role">{j.role}</span><span className="row-subtitle">{j.interviewNote||'面试形式待确认'}</span></Identity><Button variant="outline" onClick={()=>action('edit',j.id)}>调整安排</Button></div>):<div className="empty-row">暂无面试安排。填写岗位的面试时间后，会显示在这里。</div>}</CardContent></Card></section>}
function Analysis({m,distribution,channels}:any){return <section><div className="list-heading"><div><h2>投递分析</h2><p>基于 {m.total} 个岗位，了解进展与渠道分布</p></div></div><div className="analysis-grid">{[['投递状态',distribution],['投递渠道',channels]].map(([title,items]:any)=><Card key={title}><CardContent className="p-6"><h3 className="font-semibold mb-6">{title}</h3>{items.length?items.map(([label,n]:any)=><div className="chart-row" key={label}><div className="chart-label"><span>{label}</span><span>{n} 个 · {m.total?Math.round(n/m.total*100):0}%</span></div><div className="bar-track"><div className="bar-fill" style={{width:(m.total?n/m.total*100:0)+'%'}}/></div></div>):<p className="text-muted-foreground">暂无渠道数据</p>}</CardContent></Card>)}</div><p className="analysis-note">回复率 {m.rate}% =（面试 {m.interview} + Offer {m.offer}）÷ 总投递 {m.applied}。计划清单不计入总投递。</p></section>}
let dialogRoot:Element;
const api={renderSchedule:(el:Element,list:any)=>mount(el,<Schedule list={list}/>),renderAnalysis:(el:Element,p:any)=>mount(el,<Analysis {...p}/>),dispose:(el:Element)=>{const root=roots.get(el);if(root){flushSync(()=>root.unmount());roots.delete(el)}},renderJobs:(el:Element,p:any)=>mount(el,<Workspace {...p}/>),renderStats:(el:Element,m:any)=>mount(el,<Stats m={m}/>),renderNav:(el:Element,tab:string,onChange:any)=>mount(el,<Navigation tab={tab} onChange={onChange}/>),
 modal:(title:string,body:string)=>{if(!dialogRoot){dialogRoot=document.createElement('div');document.body.append(dialogRoot);}mount(dialogRoot,<Dialog open onOpenChange={open=>{if(!open)setTimeout(()=>api.closeModal(),0)}}><DialogContent className="offer-dialog" aria-describedby={undefined}><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><div className="modal-body" dangerouslySetInnerHTML={{__html:body}}/></DialogContent></Dialog>);},
 closeModal:()=>{if(dialogRoot)mount(dialogRoot,null)},
 header:(el:Element)=>{const prior=Array.from(el.querySelectorAll<HTMLButtonElement>("button")).find(b=>b.textContent==='恢复前备份');mount(el,<div className="header-buttons"><Button variant="outline" onClick={()=>action('backup')}><Download/>导出备份</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><Upload/>导入<ChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>action('csv')}>CSV 导入</DropdownMenuItem><DropdownMenuItem onSelect={()=>action('restore')}>恢复备份</DropdownMenuItem>{prior&&<DropdownMenuItem onSelect={()=>prior.click()}>恢复前备份</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu><Button className="primary-cta" onClick={()=>{const b=document.querySelector<HTMLButtonElement>('[data-tab="add"]');b?.click()}}><Plus/>添加岗位</Button></div>);}};
(window as any).OfferlyUI=api;
