const assert=require('node:assert/strict');
const L=require('../integrations/openjobtracker/workbook-library.js'),M=require('../integrations/openjobtracker/semantic-mapper.js');
const r=(record,label,value,status='已确认',mode='原样填写')=>({record,label,value,status,mode,address:'C5'});
const lib=L.compile({sourceName:'test.xlsx',sheets:[{name:'01 基础信息',rows:[r('BASE-01','中文姓名','甲'),r('BASE-01','微信号','need-check','需核对'),r('BASE-01','现居城市','')]},{name:'03 教育经历',rows:[r('EDU-01','学校中文全称','学校甲'),r('EDU-02','学校中文全称','学校乙'),r('EDU-01','学历层次','硕士研究生'),r('EDU-01','开始日期','2024-09-01'),r('EDU-02','学历层次','本科')]},{name:'04 工作与实习',rows:[r('WORK-01','完整原始描述','负责交互设计与项目验证工作','已确认','可基于事实整理')]},{name:'13 可选专项信息',rows:[r('OPT-01','证件号码','123456789012345678','已确认','人工确认后填写')]}]});
assert.equal(lib.stats.populated,9);assert.equal(lib.experiences.education.length,2);assert.equal(lib.experiences.education[0].degree,'硕士研究生');
assert.equal(lib.experiences.education[1].degree,'本科');assert.equal(lib.experiences.education[0].start,'2024-09-01');
assert(!lib.bank.some(x=>/need-check|123456789012345678/.test(x.value)));
assert.equal(lib.sheets.at(-1).rows[0].value,'123456789012345678');
const bank=M.buildBank({knowledgeLibrary:{authority:lib},userProfile:{name:'旧名字',currentCity:'旧地址'},experiences:{project:[{name:'旧项目'}]}});
assert.deepEqual(bank,lib.bank);assert(!bank.some(x=>/旧/.test(x.value)));assert.equal(lib.experiences.project.length,0);
assert(!M.compatible({label:'现居地'},bank.find(x=>x.id==='education.0.school')));
assert(!M.compatible({label:'学历'},bank.find(x=>x.id==='education.0.school')));
const protectedSource={id:'work.0.description',label:'描述',value:'负责交互设计与项目验证工作',allowRewrite:false};
const mappings=M.validateMappings([{fieldId:'f0',sourceId:protectedSource.id,confidence:1,draft:'负责交互设计',quotes:['负责交互设计']}],[{id:'f0',label:'工作描述'}],[protectedSource],0.92);
assert(!mappings[0].draft);assert(!mappings[0].quotes);
const project=L.compile({sourceName:'project.xlsx',sheets:[{name:'05 项目经历',rows:[r('PROJ-01','项目名称','测试项目'),r('PROJ-01','本人角色','交互设计'),r('PROJ-01','开始年份','2026'),r('PROJ-01','开始月份','8'),r('PROJ-01','结束年份','2026'),r('PROJ-01','结束月份','9')]}]});
assert.equal(project.experiences.project[0].role,'交互设计');
assert.equal(project.experiences.project[0].start,'2026-08');
assert.equal(project.experiences.project[0].end,'2026-09');
(async()=>{const state={userProfile:{name:'旧名字'},llmConfig:{model:'keep'},jobs:[1]};const storage={get:async keys=>Object.fromEntries(keys.map(k=>[k,state[k]])),set:async data=>Object.assign(state,data)};await L.install(storage,lib);assert.equal(state.userProfile.name,'甲');assert.equal(state.knowledgeHistory[0].userProfile.name,'旧名字');assert.equal(state.llmConfig.model,'keep');assert.deepEqual(state.jobs,[1]);assert.equal(state.knowledgeLibrary.authority.sheets.length,4);console.log('PASS authority precedence, repeated records, policy, backup, API/jobs preservation');})().catch(e=>{console.error(e);process.exitCode=1});
