const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),P=require('../../integrations/openjobtracker/v2/semantic-planner'),C=require('../../integrations/openjobtracker/v2/application-core');
const row=(title='【2027校招】 UX设计师',status='初筛')=>`<div><div>${title}</div><div>状态: <span>${status}</span></div><a>修改申请</a><span>0:28</span></div>`;
const fixtures=[['one',row()],['two',row()+row('产品设计师','面试中')],['table','<table><tbody><tr><td>【2027校招】 UX设计师</td><td>状态: 初筛</td><td>修改申请</td></tr></tbody></table>'],['list','<ul><li>'+row()+'</li></ul>'],['nested','<div><div><div>'+row()+'</div></div></div>']];
for(const [name,html] of fixtures){const dom=new JSDOM('<title>示例公司招聘</title><div>'+html+'</div>',{url:'https://example.test/applications',runScripts:'outside-only'}),w=dom.window;w.CSS={escape:x=>x};w.Element.prototype.getClientRects=()=>[{}];w.eval(fs.readFileSync('integrations/openjobtracker/v2/page-observer.js','utf8'));const page=w.PageObserver.observe();const source=page.evidence.filter(e=>e.text.includes('UX设计师')&&e.text.includes('初筛')).sort((a,b)=>a.text.length-b.text.length)[0];assert(source,name+' must expose complete single record');
const observation={regionId:source.regionId,pageKind:'application',posting:{company:'示例公司',title:'【2027校招】UX设计师'},status:{submitted:true,raw:'初筛'},evidence:[{evidenceId:source.id,regionId:source.regionId,text:'初筛',role:'application'},{evidenceId:'document-title',regionId:'page-identity',text:'示例公司',role:'identity'}]};const result=P.validateApplications({applications:[observation]},page);assert.equal(result.diagnostics.length,0,JSON.stringify(result.diagnostics));assert.equal(result.observations.length,1);const state=C.empty();C.observe(state,result.observations[0]);assert.equal(state.applications[0].state.raw,'初筛');assert(!state.applications[0].appliedAt,'clock-only text cannot become application date');
const children=page.evidence.filter(e=>page.regions.find(r=>r.id===e.regionId)?.ancestorIds?.includes(source.regionId));const titleChild=children.find(e=>e.text.includes('UX设计师')&&!e.text.includes('初筛')),statusChild=children.find(e=>e.text.includes('初筛')&&!e.text.includes('UX设计师'));if(titleChild&&statusChild){const split=structuredClone(observation);split.evidence=[...[titleChild,statusChild].map(e=>({evidenceId:e.id,regionId:e.regionId,text:e.text,role:'application'})),observation.evidence[1]];assert.equal(P.validateApplications({applications:[split]},page).observations.length,1,'title and status descendants of same record can be combined');}
const invented=structuredClone(observation);invented.posting.title='算法工程师';assert(P.validateApplications({applications:[invented]},page).diagnostics.length);
const wrong=structuredClone(observation);wrong.status.raw='面试中';assert(P.validateApplications({applications:[wrong]},page).diagnostics.length,'other record status cannot enter selected record');
const cut={...page,coverage:{contentTruncated:true}};assert(P.validateApplications({applications:[observation]},cut).diagnostics.some(d=>d.code==='INCOMPLETE_PAGE_COVERAGE'));dom.window.close();}
console.log('PASS application layouts: single/div/table/list/nested, whitespace, source-resolved quote, no invented title or sibling status, incomplete coverage explicit');
