const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const C=require('../../integrations/openjobtracker/v2/application-core');
(async()=>{
 const state=C.empty(),listeners=[];let calls=0,exports=0;const storage={excelConfig:{autoExport:true}};
 class Repo{async snapshot(){return structuredClone(state);}async transact(fn){return fn(state);}async session(k,fn){if(fn)state.sessions[k]=fn(state.sessions[k]);return structuredClone(state.sessions[k]);}async observe(o){return C.observe(state,o).result;}}
 const sender={id:'extension',frameId:0,url:'https://careers.example.test/status',tab:{id:1}};
 const ctx={console,URL,Promise,Date,ApplicationCore:C,EasyOfferRepository:Repo,getLlmConfig:async()=>({}),SemanticMapper:{buildBank:()=>[]},SemanticPlanner:{applicationExcluded:require('../../integrations/openjobtracker/v2/semantic-planner').applicationExcluded,plan:async(purpose,page)=>{calls++;return {observations:[{id:'observation-'+calls,regionId:'card',site:page.site,url:page.url,pageKind:'application',observedAt:page.observedAt,sourceApplicationId:'A1',posting:{company:'示例公司',title:'设计师'},status:{submitted:true,raw:'简历评估'},evidence:[{regionId:'card',role:'current',text:'示例公司 设计师 简历评估'}]}],tools:[]};}},ApplicationExcel:{exportSnapshot:async()=>{exports++;throw Error('Excel unavailable');}},chrome:{runtime:{id:'extension',getURL:p=>'chrome-extension://extension/'+p,getManifest:()=>({version:'4.0.0'}),onMessage:{addListener:f=>listeners.push(f)}},storage:{local:{get:async()=>storage,set:async()=>{}},onChanged:{addListener(){}}},scripting:{getRegisteredContentScripts:async()=>[]},permissions:{onAdded:{addListener(){}},onRemoved:{addListener(){}}}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('integrations/openjobtracker/v2/background-runtime.js','utf8'),ctx);
 const call=(m,s=sender)=>new Promise(resolve=>listeners[0](m,s,resolve));
 const page={site:'https://careers.example.test',url:sender.url,observedAt:100,taskId:'first',fingerprint:'fp',regions:[{id:'card',text:'简历评估'}]};
 const first=await call({type:'EASY_V2_PLAN',purpose:'application',page});assert.equal(first.ok,true);const initial=await call({type:'EASY_V2_APPLY_OBSERVATIONS',observations:first.result.observations});assert.equal(initial.ok,true,initial.error);const id=state.applications[0].id;
 C.command(state,{operationId:'edit',applicationId:id,baseRevision:1,patch:{status:'笔试'}});const revision=state.revision,events=state.events.length;
 const repeat=await call({type:'EASY_V2_PLAN',purpose:'application',page:{...page,observedAt:200,taskId:'second'}});assert.equal(repeat.result.cacheHit,true);assert.equal(calls,1);assert.equal(repeat.result.observations[0].observedAt,200);
 const replay=await call({type:'EASY_V2_APPLY_OBSERVATIONS',observations:repeat.result.observations});assert.equal(replay.result.results[0].applicationId,id);assert.equal(replay.result.results[0].revision,state.applications[0].revision);assert.equal(state.revision,revision);assert.equal(state.events.length,events);assert.equal(state.applications[0].state.stage,'written');assert.equal(exports,2,'manual repeat retries delivery without reinterpreting unchanged evidence');assert.equal(replay.result.excel.pending,true);
 await call({type:'EASY_V2_PLAN',purpose:'application',page:{...page,regions:[{id:'card',text:'筛选中'}]}});assert.equal(calls,2,'changed evidence invalidates cache even with an identical short fingerprint');
 const next={...sender,url:'https://careers.example.test/other'};await call({type:'EASY_V2_PLAN',purpose:'application',page:{...page,url:next.url}},next);assert.equal(calls,3,'separate page has separate memory');
 storage.easyOfferV2={excludeInternships:true};await call({type:'EASY_V2_PLAN',purpose:'application',page:{...page,url:next.url}},next);assert.equal(calls,4,'scope changes invalidate cached plans');
 const count=state.applications.length;const skipped=await call({type:'EASY_V2_APPLY_OBSERVATIONS',observations:[{...first.result.observations[0],posting:{company:'示例公司',title:'设计师实习生'}}]});assert.equal(skipped.ok,true);assert.equal(skipped.result.results.length,0);assert.equal(skipped.result.excluded.length,1);assert.equal(state.applications.length,count,'authority must also reject excluded jobs from older in-flight plans');
 console.log('PASS page memory: validated understanding replay, no model drift or manual overwrite, delivery retry, exact evidence and URL invalidation');
})().catch(e=>{console.error(e);process.exitCode=1;});
