// Synthetic Moka-shaped DOM. No user data or live employer page is included.
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),{bank:projectBank,projects}=require('./data.cjs');
const imported=projectBank.map(({recordId,source,...f})=>({...f,...(f.kind==='date'?{}:{source:{record:recordId}})}));
const bank=[...imported,{id:'profile.gender',recordId:'profile',label:'性别',value:'男',kind:'text'},{id:'award.0.name',recordId:'AWARD',label:'奖项名称',value:'设计比赛三等奖',kind:'text'},{id:'award.0.date',recordId:'AWARD',label:'获奖时间',value:'2025-10-01',kind:'date'}];
const P=require('../../integrations/openjobtracker/v2/semantic-planner');global.ModelGateway=require('../../integrations/openjobtracker/v2/model-gateway');
if(process.env.LIVE_MODEL_CONFIG){const invoke=ModelGateway.invoke;let n=0;ModelGateway.invoke=async req=>{const output=await invoke(req);fs.mkdirSync('work/xunlei-4.0',{recursive:true});fs.writeFileSync('work/xunlei-4.0/synthetic-model-'+(++n)+'.json',JSON.stringify({page:req.input.page,output},null,2));return output;};}
(async()=>{let session={},last,calls=0;const config=process.env.LIVE_MODEL_CONFIG?JSON.parse(fs.readFileSync(process.env.LIVE_MODEL_CONFIG)):null;
const dom=new JSDOM(fs.readFileSync('tests/v2/fixtures/split-controls.html','utf8'),{url:'https://careers.example.test/form',runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){
 w.structuredClone=structuredClone;w.CSS={escape:s=>s};w.Element.prototype.getClientRects=function(){return this.closest('[hidden]')?[]:[{width:300,height:40}];};w.Element.prototype.getBoundingClientRect=()=>({width:300,height:40,top:0,left:0,bottom:40,right:300});w.Element.prototype.scrollIntoView=()=>{};
 w.chrome={runtime:{onMessage:{addListener:()=>{},removeListener:()=>{}},sendMessage:async m=>{
  if(m.type==='OJT_AGENT_RESUME')return {resume:false};
  if(m.type==='EASY_V2_SESSION'){if(m.patch)session=structuredClone(m.patch);return {ok:true,result:structuredClone(session)};}
  if(m.type==='EASY_V2_PLAN'){calls++;const page=m.page;let result;if(config)result=await P.plan('form',page,bank,session,config,{toolResults:m.toolResults,feedback:m.feedback});else{
   const blocks=page.regions.filter(r=>r.fieldIds.length).map(r=>{const el=w.document.querySelector(r.locator),i=el.id.match(/experience(\d)/)?.[1],recordId=i?projects[+i-1].recordId:el.id==='award'?'AWARD':'profile';return {regionId:r.id,recordId,allowedTypes:[i?'project':el.id==='award'?'award':'profile'],evidence:[{regionId:r.id,text:r.text.slice(0,30)}],fields:page.fields.filter(f=>f.regionId===r.id&&f.type!=='checkbox').map(f=>{const name=w.document.querySelector(f.locator).name;return {fieldId:f.id,sourceIds:[i?'project.'+(+i-1)+'.'+(name.startsWith('start')?'start':name.startsWith('end')?'end':name.startsWith('duties')?'role':name.replace(/\d/g,'')):name==='gender'?'profile.gender':name==='awardName'?'award.0.name':'award.0.date']};})};});result=w.SemanticPlanner.validateForm({blocks},page,bank,session);
   }return {ok:true,result};}return {ok:true};}},storage:{local:{get:async()=>({knowledgeLibrary:{authority:{active:true,bank}},experiences:{}})}}};
}});const w=dom.window;for(const file of ['ui-icons.js','job-validator.js','semantic-mapper.js','content.js','application-agent.js','v2/page-observer.js','v2/semantic-planner.js','v2/form-adapter.js','agent-dom.js'])w.eval(fs.readFileSync('integrations/openjobtracker/'+file,'utf8'));
const input=name=>w.document.querySelector(`[name="${name}"]`),shown=name=>w.OJTFormCore.displayedControlValue(input(name));
let page=w.PageObserver.observe();for(let i=1;i<=2;i++){const r=page.regions.find(r=>r.locator==='#experience'+i);assert(r,'entire record is a region');assert.equal(r.fieldIds.length,9,'dates and text share one record');const f=page.fields.find(f=>f.locator===w.PageObserver.path(input('endMonth'+i)));assert.equal(f.datePart,'month');assert.equal(f.dateEdge,'end');assert(r.ancestorIds.some(id=>page.regions.find(r=>r.id===id).heading==='项目经验'));}
input('awardYear').value='2025-10-01';assert.equal(shown('awardYear'),'','search text is not a selection');assert.equal(w.PageObserver.observe().fields.find(f=>f.locator===w.PageObserver.path(input('awardYear'))).current,'');input('awardYear').value='';
assert.deepEqual(Array.from(await w.PageObserver.readOptions(page.fields.find(f=>f.locator===w.PageObserver.path(input('gender'))).id),o=>o.text),['男','女'],'menu read excludes navigation and duplicate labels');
const oldRegion=w.PageObserver.path(input('startYear1').closest('.month-range-select')),locator=w.PageObserver.path(input('startYear1'));
const stale={bindings:{[oldRegion]:{recordId:projects[0].recordId,regionLocator:oldRegion}},owners:{[projects[0].recordId]:oldRegion},operations:{[locator]:{recordId:projects[0].recordId,locator,expected:projects[0].start,status:'undone'}}};
assert.equal(Object.keys(P.reconcileFormSession(stale,page).owners).length,0,'undone empty date wrapper releases ownership');
input('startYear1').parentElement.querySelector('span').textContent='2025';stale.operations[locator].status='verified';stale.operations[locator].after='2025';
assert.equal(P.reconcileFormSession(stale,w.PageObserver.observe()).owners[projects[0].recordId],'#experience1','verified date ownership moves to whole experience');input('startYear1').parentElement.querySelector('span').textContent='';session=stale;session.operations[locator].status='failed';
const run=w.ApplicationAgent.Runner.prototype.run;w.ApplicationAgent.Runner.prototype.run=function(){w.activeRunner=this;return run.call(this);};const emit=w.ApplicationAgent.Runner.prototype.emit;w.ApplicationAgent.Runner.prototype.emit=function(m,e){last={message:m,status:this.status};return emit.call(this,m,e);};
async function start(){last=null;await new Promise(resolve=>w.__ojtAgentListener({type:'START_APPLICATION_AGENT'},{},resolve));for(let i=0;i<2400;i++){await new Promise(r=>setTimeout(r,25));if(last&&['done','blocked','stopped'].includes(last.status))return;}throw Error('timeout');}
await start();assert(['blocked','done'].includes(last.status),JSON.stringify(last));
for(let i=1;i<=2;i++){const p=projects[i-1];for(const key of ['name','role'])assert.equal(shown(key+i),p[key]);
 const description=shown('description'+i);assert.equal(description,p.description,'ordinary description must retain the complete original');assert(description.includes(p.description.split('。')[0]),'project background retained');assert(description.includes(p.description.split('。')[2]),'project delivery retained');assert(description.split('\n').every(q=>p.description.includes(q)),'description is entirely sourced');assert(shown('duties'+i)===p.role||p.description.includes(shown('duties'+i)),'responsibility stays sourced');for(const edge of ['start','end']){const [year,month]=p[edge].split('-');assert.equal(shown(edge+'Year'+i),year);assert.equal(shown(edge+'Month'+i),String(+month));assert.equal(input(edge+'Year'+i).value,'');const observed=w.PageObserver.observe().fields.find(f=>f.locator===w.PageObserver.path(input(edge+'Year'+i)));assert.equal(observed.datePart,'year');assert.equal(observed.dateEdge,edge,'selection must not change date identity');}}
assert.equal(shown('gender'),'男');assert.equal(shown('awardYear'),'2025');assert.equal(shown('awardMonth'),'10');assert.equal(shown('awardName'),'设计比赛三等奖');assert.equal(Object.values(session.operations).filter(o=>o.status==='verified').length,20);
const before=JSON.stringify(w.PageObserver.observe().fields.map(f=>f.current));await start();assert.equal(JSON.stringify(w.PageObserver.observe().fields.map(f=>f.current)),before,'repeat keeps committed values');assert.equal(Object.keys(session.owners).length,4);assert.equal(w.submissions,0);assert.equal(w.saves,0);
console.log((config?'REAL MODEL / JSDOM ':'')+'PASS split controls: 2 complete records, 10 date segments, committed select readback, stale ownership recovery, repeat, no save/submit ('+calls+' model calls)');w.activeRunner.stop();dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
