const assert=require('node:assert/strict'),C=require('../../integrations/openjobtracker/v2/application-core');
const s=C.empty();let o={id:'first',site:'https://example.test',observedAt:Date.now()-864000000,pageKind:'application',sourceApplicationId:'A1',posting:{company:'测试企业',title:'设计师'},status:{submitted:true,raw:'初筛'},evidence:[{regionId:'card',role:'current',text:'初筛'}]};C.observe(s,o);const a=s.applications[0],id=a.id;
assert.deepEqual(C.statusActions(C.toView(a)).map(x=>x.status),['笔试','面试中','未通过','已撤回']);assert.equal(a.statusSource,'official_site');assert.equal(s.events[0].source,'official_site');const checked=a.lastObservedAt;
function change(status,op,source='manual'){return C.command(s,{operationId:op,applicationId:id,baseRevision:a.revision,source,patch:{status}}).result;}
change('面试中','direct');assert.equal(a.statusSource,'manual');assert.equal(a.lastObservedAt,checked);assert.deepEqual(C.statusActions(C.toView(a)).map(x=>x.status),['Offer','未通过','已撤回']);const st=a.statusUpdatedAt;C.command(s,{operationId:'note',applicationId:id,baseRevision:a.revision,patch:{notes:'备注'}});assert.equal(a.statusUpdatedAt,st);assert.equal(a.lastObservedAt,checked);assert.match(C.statusInfo(C.toView(a)).primary,/手动更新/);assert.match(C.statusInfo(C.toView(a)).secondary,/10 天未检查/);
// Changed metadata alone must not erase a manual interview status.
C.observe(s,{...o,id:'metadata',observedAt:Date.now(),posting:{...o.posting,city:'北京'}});assert.equal(a.state.stage,'interview');assert.equal(a.statusSource,'manual');
change('未通过','reject');assert.equal(C.statusActions(C.toView(a)).length,0);C.command(s,{operationId:'undo',applicationId:id,baseRevision:a.revision,undoOf:'reject'});assert.equal(a.state.stage,'interview');assert.equal(a.statusSource,'manual');change('Offer','offer');assert.equal(C.statusActions(C.toView(a)).length,0);change('已撤回','withdraw');assert.equal(C.statusActions(C.toView(a)).length,0);
change('笔试','written','agent');assert.equal(a.statusSource,'agent');assert.equal(s.events.at(-1).source,'agent');assert.deepEqual(C.statusActions(C.toView(a)).map(x=>x.status),['面试中','未通过','已撤回']);const rev=a.revision;C.command(s,{operationId:'later-note',applicationId:id,baseRevision:rev,patch:{notes:'并发修改'}});assert(C.command(s,{operationId:'stale-undo',applicationId:id,baseRevision:rev,undoOf:'written'}).result.conflict);
o={...o,id:'new-state',observedAt:Date.now()+1,status:{submitted:true,raw:'面试中'},evidence:[{regionId:'card',role:'current',text:'面试中'}]};C.observe(s,o);assert.equal(a.id,id);assert.equal(a.statusSource,'official_site');const count=s.events.length;C.observe(s,{...o,id:'repeat',observedAt:o.observedAt+1});assert.equal(s.events.length,count);assert.equal(a.lastStatusObservedAt,o.observedAt+1);
assert.equal(C.statusInfo({status:'已投递'}).primary,'尚未读取官网状态');assert.match(C.statusInfo({statusSource:'manual',statusUpdatedAt:Date.now()}).secondary,/尚未读取/);console.log('PASS status operations: contextual transitions, sources, scoped undo/conflict, official clocks, stable ID, manual protection and idempotent observations');
