// Deterministic model-output fixture -> production observer/validator/core -> real XLSX projection and editable desk bridge.
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const C=require('../../integrations/openjobtracker/v2/application-core'),P=require('../../integrations/openjobtracker/v2/semantic-planner');global.ApplicationCore=C;global.XLSX=require('../../vendor/sheetjs/xlsx.full.min');const E=require('../../integrations/openjobtracker/v2/excel-export');
const liveConfig=process.env.LIVE_MODEL_CONFIG?JSON.parse(fs.readFileSync(process.env.LIVE_MODEL_CONFIG,'utf8')):null;global.ModelGateway=require('../../integrations/openjobtracker/v2/model-gateway');const liveMetrics=[];
const tick=()=>new Promise(r=>setTimeout(r,20));
(async()=>{let state=C.empty();C.migrate(state,[{id:'legacy-one',company:'示例科技',role:'产品设计师',status:'已投递',notes:'旧备注',url:'https://careers.example.test/applications'}],'migration');const id=state.applications[0].id;
const page=new JSDOM(fs.readFileSync('tests/v2/fixtures/status.html','utf8'),{url:'https://careers.example.test/applications',runScripts:'outside-only'});const w=page.window;w.CSS={escape:s=>s};w.Element.prototype.getClientRects=()=>[{}];w.eval(fs.readFileSync('integrations/openjobtracker/v2/page-observer.js','utf8'));
async function observe(raw,stub=false){const snapshot=w.PageObserver.observe(),r=snapshot.regions.find(r=>r.locator==='#application'),e=snapshot.evidence.find(e=>e.locator==='#application'),current=snapshot.evidence.find(e=>e.locator==='#current');const model={applications:[{regionId:r.id,pageKind:'application',sourceApplicationId:'APP-DEMO-1',sourceJobId:'JOB-DEMO-1',posting:{company:'示例科技',title:w.document.getElementById('job-title').textContent,city:w.document.getElementById('city').textContent},status:{submitted:true,raw},preferences:[{id:'P1',label:'第一意向：体验设计部',rawStatus:'等待评估'},{id:'fake',label:'编造部门',rawStatus:'Offer'}],evidence:[{evidenceId:e.id,regionId:r.id,text:e.text,role:'application'},{evidenceId:current.id,regionId:r.id,text:current.text,role:'current'}]}]};if(liveConfig&&!stub){const result=await P.plan('application',snapshot,[],{},liveConfig,{fetcher:(url,init)=>fetch(url,{...init,headers:{...init.headers,'Accept-Encoding':'identity'}}),onMetric:m=>liveMetrics.push(m)});fs.mkdirSync('work/v2-live',{recursive:true});fs.writeFileSync('work/v2-live/sync-model.json',JSON.stringify({kind:'real-model-jsdom-controls',metrics:liveMetrics,observations:result.observations},null,2));assert.equal(result.observations.length,1,'AI should extract one application');return result.observations;}return P.validateApplications(model,snapshot).observations;}
assert.equal((await observe('Offer',true)).length,0,'future Offer is not current');C.observe(state,(await observe('简历评估'))[0]);assert.equal(state.applications[0].id,id);assert.equal(state.applications[0].preferences.length,1);
w.document.getElementById('job-title').textContent='2027届产品设计师';w.document.getElementById('current').textContent='筛选中';w.document.getElementById('city').textContent='北京';C.observe(state,(await observe('筛选中'))[0]);const events=state.events.length;C.observe(state,(await observe('筛选中'))[0]);assert.equal(state.events.length,events);assert.equal(state.applications.length,1);
// Preserve the previous workbook, fail one write, and retry the same authoritative projection.
let fail=true,written,old=XLSX.utils.book_new();XLSX.utils.book_append_sheet(old,XLSX.utils.aoa_to_sheet([['原表'],['保留']]),'旧投递');
global.ExcelStore={queryPermission:async()=> 'granted',getHandle:async()=>({getFile:async()=>({arrayBuffer:async()=>XLSX.write(old,{type:'array',bookType:'xlsx'})}),createWritable:async()=>({write:async bytes=>{if(fail)throw Error('模拟磁盘失败');written=bytes;},close:async()=>{},abort:async()=>{}})})};
await assert.rejects(E.exportSnapshot(state),/模拟磁盘失败/);assert.equal(state.applications.length,1);fail=false;await E.exportSnapshot(state);await E.exportSnapshot(state);const exported=XLSX.read(written,{type:'array'});const rows=XLSX.utils.sheet_to_json(exported.Sheets['EasyOffer权威记录'],{header:1});assert.equal(rows.length,2);assert.equal(rows[1][0],id);assert.equal(rows[1][6],'筛选中');assert.equal(exported.Sheets['旧投递'].A2.v,'保留');
const desk=new JSDOM('<div id="extension-status"></div>',{url:'https://autumn-career-desk-qpc.linyouju.chatgpt.site',runScripts:'outside-only'}),d=desk.window;d.structuredClone=structuredClone;d.ApplicationCore=C;d.KEY='desk';d.jobs=[C.toView(state.applications[0])];d.$=s=>d.document.querySelector(s);d.validateRecord=r=>r;d.render=()=>{};d.persist=next=>{d.EasyOfferDesk?.capture(d.jobs,next);d.jobs=next;d.localStorage.setItem(d.KEY,JSON.stringify(next));};d.HTMLDialogElement.prototype.showModal=function(){this.open=true;};d.HTMLDialogElement.prototype.close=function(){this.open=false;};d.localStorage.setItem('easyoffer-v2-migrated','true');
const send=data=>d.dispatchEvent(new d.MessageEvent('message',{source:d,origin:d.location.origin,data}));let ack=0;
d.postMessage=m=>{if(m.type!=='EASY_V2_DESK_REQUEST')return;let result;const c=m.command;if(c.kind==='query')result={revision:state.revision,records:state.applications.map(C.toView)};else if(c.kind==='edit')result=C.command(state,c).result;else if(c.kind==='ack'){assert.equal(JSON.parse(d.localStorage.getItem(d.KEY))[0].revision,c.records[0].revision);ack++;result={ok:true};}setTimeout(()=>send({type:'EASY_V2_DESK_RESPONSE',requestId:m.requestId,ok:true,result}),0);};d.eval(fs.readFileSync('integrations/openjobtracker/v2/desk-client.js','utf8'));
// Edit offline, then receive a conflicting new authority revision before connecting.
d.persist(d.jobs.map(r=>({...r,notes:'离线备注'})));assert.equal(d.EasyOfferDesk.pending().length,1);C.command(state,{operationId:'other',applicationId:id,baseRevision:state.applications[0].revision,patch:{notes:'另一处新备注'}});send({type:'EASY_V2_HELLO'});for(let i=0;i<20&&!d.document.querySelector('dialog');i++)await tick();assert(d.document.querySelector('dialog'));assert.equal(d.EasyOfferDesk.pending().length,1);
[...d.document.querySelectorAll('button')].find(b=>b.textContent==='采用我的修改').click();for(let i=0;i<30&&d.EasyOfferDesk.pending().length;i++)await tick();await tick();assert.equal(C.toView(state.applications[0]).notes,'离线备注');assert.equal(d.jobs[0].applicationId,id);assert.equal(d.jobs[0].rawStatus,'筛选中');assert(ack>0);assert.equal(d.EasyOfferDesk.pending().length,0);
console.log((liveConfig?'REAL MODEL / JSDOM ':'')+'PASS sync flow: scoped state evidence, stable ID, preferences, replay, XLSX failure/retry/preservation, offline conflict choice, mirror save before ACK');page.window.close();desk.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
