(function(root){'use strict';
const rpc=async m=>{const r=await chrome.runtime.sendMessage(m);if(!r?.ok)throw Error(r?.error||'任务服务未响应');return r.result;};
function create(base,bank){let session,taskId=crypto.randomUUID(),lastPlan,attempts={},calls=0,stopped=false,edited=new Set(),lastPage,newRun=true,planningRounds=0;const strategies=new Map(),verified=new Set();
 const key=f=>f.locator;const resolve=item=>{item.el=document.querySelector(item.locator);return item.el;};
 const userEdit=e=>{if(!e.isTrusted)return;if(e.type!=='pointerdown'&&e.target.matches('input,textarea,select,[contenteditable=true]'))edited.add(PageObserver.path(e.target));for(const f of lastPlan?.fields||[])if(f.dateGroup&&document.querySelector(f.locator)?.contains(e.target))edited.add(f.locator);};let listening=false;const attach=()=>{if(listening)return;listening=true;for(const name of ['input','change','pointerdown'])document.addEventListener(name,userEdit,true);};const detach=()=>{listening=false;for(const name of ['input','change','pointerdown'])document.removeEventListener(name,userEdit,true);};attach();
 const canReplace=(item,value)=>Boolean(item.dateGroup&&session.operations?.[key(item)]?.implicitValue===value&&value&&!edited.has(item.locator)&&!session.userEdited?.includes(item.locator));
 const save=()=>{session.taskStats={taskId,planningRounds,replans:Math.max(0,planningRounds-1),copy:[...strategies.values()].filter(x=>x==='copy').length,format:[...strategies.values()].filter(x=>x==='format').length,transform:[...strategies.values()].filter(x=>x==='transform').length,missing:lastPlan?.missing?.length||0,successfulFields:verified.size,userEditedFields:edited.size,stopped,updatedAt:Date.now()};session.userEdited=[...new Set([...(session.userEdited||[]),...edited])];return rpc({type:'EASY_V2_SESSION',patch:session});};
 return {...base,
 cancel(){stopped=true;if(session)save().catch(()=>{});rpc({type:'EASY_V2_CANCEL',taskId}).catch(()=>{});detach();},
 async observe(){if(newRun){edited.clear();attach();}lastPage=PageObserver.observe();lastPage.taskId=taskId;session=SemanticPlanner.reconcileFormSession(await rpc({type:'EASY_V2_SESSION'}),lastPage,{newRun});newRun=false;await save();session.bindings||={};session.owners||={};session.operations||={};if(session.actionIntent?.fields&&lastPage.fields.some(f=>!session.actionIntent.fields.includes(f.locator))){session.actionIntent=null;await save();}return {page:lastPage,url:location.href,signature:lastPage.fingerprint};},
 async plan(snapshot){planningRounds++;if(stopped)throw Error('STOPPED');if(++calls>5)throw Error('已达到本次页面理解预算，已填内容保留');let plan=await rpc({type:'EASY_V2_PLAN',purpose:'form',page:snapshot.page,replanReason:planningRounds>1?'page-or-control-changed':null,feedback:Object.values(session.operations).filter(o=>o.status==='failed').map(o=>({label:o.label,error:o.error}))});
 if(stopped)throw Error('STOPPED');
 plan=await SemanticPlanner.continueTools(plan,snapshot.page,{observer:PageObserver,isCancelled:()=>stopped,beforeRequest:()=>{if(++calls>5)throw Error('已达到本次页面理解预算');},request:(page,toolResults)=>rpc({type:'EASY_V2_PLAN',purpose:'form',page,toolResults})});
 if(stopped)throw Error('STOPPED');
 const fields=plan.fields.filter(f=>!edited.has(f.locator)&&!session.userEdited?.includes(f.locator)&&(attempts[key(f)]||0)<3);
 for(const f of fields){strategies.set(f.recordId+'|'+f.locator,f.strategy||'copy');session.bindings[f.binding.regionLocator]=f.binding;session.owners[f.recordId]=f.binding.regionLocator;session.operations[key(f)]={...(session.operations[key(f)]||{}),recordId:f.recordId,sourceIds:f.sourceIds,locator:f.locator,label:f.label,status:'planned',expected:f.value};f.source={...f.source,value:f.value};resolve(f);}
 session.taskId=taskId;session.userEdited=[...new Set([...(session.userEdited||[]),...edited])];await save();lastPlan={fields,action:plan.action,missing:plan.missing||[],diagnostics:plan.diagnostics||[]};return lastPlan;
 },
 async valid(item,snapshot){if(stopped||location.href!==snapshot.url||edited.has(item.locator))return false;const el=resolve(item);if(!el||!PageObserver.visible(el)||PageObserver.value(el)&&!canReplace(item,PageObserver.value(el)))return false;const current=PageObserver.observe().fields.find(f=>f.locator===item.locator);return current&&!current.forbidden&&current.label===item.label&&session.owners[item.recordId]===item.binding.regionLocator;},
 canReplace,
 async read(item){const el=resolve(item);return el?PageObserver.value(el):'';},
 async write(item){if(item.sourceVersions?.length){const fresh=await rpc({type:'EASY_V2_PROFILE_CHECK',sources:item.sourceVersions});if(!fresh.valid){session.operations[key(item)].status='failed';session.operations[key(item)].error='来源资料已更新，请重新规划';await save();return false;}}if(stopped||edited.has(item.locator))return false;const op=session.operations[key(item)];op.status='intent';op.before=PageObserver.value(item.el);await save();if(stopped||edited.has(item.locator)||PageObserver.value(item.el)&&!canReplace(item,PageObserver.value(item.el)))return false;attempts[key(item)]=(attempts[key(item)]||0)+1;
 const el=resolve(item);if(!el||PageObserver.value(el)&&!canReplace(item,PageObserver.value(el))||!PageObserver.visible(el))return false;
 const related=item.dateGroup?(lastPlan?.fields||[]).filter(f=>f.locator!==item.locator&&f.dateGroup===item.dateGroup):[];
 const prior=new Map(related.map(f=>[f.locator,(document.querySelector(f.locator)?PageObserver.value(document.querySelector(f.locator)):'')]));
 let ok;if(['checkbox','radio'].includes(el.type)){const label=OJTFormCore.getFieldDescriptor(el);ok=String(item.value)===String(el.value)||String(item.value)===label;if(ok&&!el.checked)el.click();}else ok=await OJTFormCore.writeMappedField(el,item.source,canReplace(item,PageObserver.value(el)),true);
 // Selecting a year can default an untouched month to January. Only defaults
 // observed during this exact write may be replaced, never pre-existing values.
 for(const f of related){const node=document.querySelector(f.locator);if(!node)continue;const before=prior.get(f.locator),after=PageObserver.value(node);if(after&&after!==before&&(!before||canReplace(f,before))&&!edited.has(f.locator))session.operations[key(f)].implicitValue=after;}
 op.after=resolve(item)?PageObserver.value(item.el):'';op.status=ok?'written':'failed';op.error=ok?'':'控件未接受来源值';await save();return ok;
 },
 async verify(item){await new Promise(r=>setTimeout(r,200));const shown=await this.read(item);const el=resolve(item);const ok=['checkbox','radio'].includes(el?.type)?Boolean(el.checked&&(String(item.value)===el.value||String(item.value)===OJTFormCore.getFieldDescriptor(el))):item.source.kind==='date'?Boolean(el&&OJTFormCore.dateControlMatches(el,item.value)):String(shown).trim()===String(item.value).trim();const op=session.operations[key(item)];op.status=ok?'verified':'failed';if(ok)verified.add(item.recordId+'|'+item.locator);op.after=shown;await save();return ok;},
 async check(snapshot,plan){const now=PageObserver.observe();const newFields=now.fields.some(f=>!snapshot.page.fields.some(x=>x.locator===f.locator));if(newFields&&calls<5)return {rescan:true};const failed=plan.fields.filter(f=>session.operations[key(f)]?.status==='failed'&&(attempts[key(f)]||0)<3);if(failed.length&&calls<5)return {rescan:true};
 const action=lastPlan.action;if(action&&!stopped){const missing=now.fields.filter(f=>!f.forbidden&&!f.current&&f.required);if(!missing.length||/编辑|展开/.test(action.label))return {missing:[],action:{...action,key:action.locator,kind:/添加|新增|add/i.test(action.label)?'add':/编辑|edit/i.test(action.label)?'edit':'expand',section:'AI已确认区块'}};}
 return {missing:now.fields.filter(f=>!f.forbidden&&!f.current&&!edited.has(f.locator)&&(f.required||lastPlan.missing.some(m=>m.fieldId===f.id)||session.operations[f.locator]?.status==='failed')).map(f=>{const missing=lastPlan.missing.find(m=>m.fieldId===f.id),op=session.operations[f.locator];return (op?.status==='failed'?'控件未接受填写：':missing?'缺少资料：':'必填项尚未完成：')+f.label+(missing?'（'+missing.reason+'）':'');})};
 },
 async act(action){if(stopped||session.actionIntent?.locator===action.locator)return false;const el=document.querySelector(action.locator);if(!el||!PageObserver.visible(el)||/提交|投递|申请|同意|删除|保存/i.test(el.textContent))return false;const before=PageObserver.observe().fingerprint;session.actionIntent={locator:action.locator,before,fields:PageObserver.observe().fields.map(f=>f.locator)};await save();if(stopped)return false;el.click();for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,150));if(stopped)return false;if(PageObserver.observe().fingerprint!==before){session.actionIntent=null;await save();return true;}}return false;},
 async restore(entry){const el=resolve(entry.item);if(!el||edited.has(entry.item.locator)||PageObserver.value(el)!==entry.after)return;if(['checkbox','radio'].includes(el.type)){el.checked=Boolean(entry.before);el.dispatchEvent(new Event('change',{bubbles:true}));}else await base.restore({...entry,item:{...entry.item,el}});if(session.operations[key(entry.item)])session.operations[key(entry.item)].status='undone';verified.delete(entry.item.recordId+'|'+entry.item.locator);await save();},
 checkpoint:async()=>save(),clearCheckpoint:async()=>{if(session)await save();detach();newRun=true;}
 };
}
root.EasyFormAdapter={create};
})(globalThis);
