(async()=>{'use strict';
const $=id=>document.getElementById(id), rpc=async(action,body={})=>{const r=await chrome.runtime.sendMessage({type:'EASY_PROFILE',action,...body});if(!r?.ok)throw Error(r?.error||'资料服务未响应');return r.result;};let profile,preview=[];
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const status=t=>$('profile-status').textContent=t;
const run=fn=>async()=>{try{await fn();}catch(e){status(e.message);}};
async function load(){profile=await rpc('get');render();}
function download(wb,name){const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'}),url=URL.createObjectURL(new Blob([bytes]));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function apply(changes){const result=await rpc('apply',{command:{operationId:crypto.randomUUID(),changes}});profile=result.profile;render();status('已更新。下次填写使用这里的资料；未修改的字段保持有效。');}
function render(){
 $('profile-current').textContent=`当前资料库 · ${profile.records.length} 条记录 · 最近更新 ${new Date(profile.updatedAt).toLocaleString()} · 版本 ${profile.revision}`;
 const host=$('profile-records');host.replaceChildren();
 for(const type of ProfileCore.types){const records=profile.records.filter(r=>r.type===type);if(!records.length)continue;host.append(el('h3',ProfileCore.labels[type]));for(const record of records){const section=el('details');const title=record.fields.find(f=>['name','company','school'].includes(f.key)&&f.value)?.value||record.id;section.append(el('summary',title));const changes=[];
 for(const field of record.fields){const wrap=el('div');wrap.className='field';const label=el('label',field.label);const input=el('textarea');input.rows=field.value.length>120?5:2;input.value=field.value;input.setAttribute('aria-label',field.label);const confirmed=el('select');for(const value of ['已确认','需核对','未确认']){const opt=el('option',value);opt.value=value;confirmed.append(opt);}confirmed.value=field.status;confirmed.setAttribute('aria-label',field.label+'确认状态');const mode=el('select');for(const value of ['原样填写','可基于事实整理','人工确认后填写']){const opt=el('option',value);opt.value=value;mode.append(opt);}mode.value=field.mode;mode.setAttribute('aria-label',field.label+'填写规则');label.append(input);wrap.append(label,confirmed,mode);section.append(wrap);changes.push(()=>({recordId:record.id,fieldId:field.id,baseRevision:field.revision,oldValue:field.value,patch:{value:input.value,status:confirmed.value,mode:mode.value}}));}
 const save=el('button','保存这条记录');save.className='btn-2';save.onclick=run(()=>apply(changes.map(f=>f())));section.append(save);
 const add=el('button','增加字段');add.className='btn-2';add.onclick=()=>{const label=prompt('字段名称');if(!label?.trim())return;const value=prompt('填写内容（可以留空）');if(value===null)return;run(()=>apply([{recordId:record.id,fieldId:crypto.randomUUID(),newField:{key:'field_'+crypto.randomUUID().replaceAll('-',''),label:label.trim(),value}}]))();};section.append(add);host.append(section);}}
 $('profile-undo').disabled=!profile.history.some(h=>!h.undone);
}
function showDiff(changes){preview=changes;const host=$('profile-preview');host.replaceChildren();for(const [i,c]of changes.entries()){const label=el('label');label.style='display:block;white-space:pre-wrap;padding:12px;border-bottom:1px solid #ddd';const check=el('input');check.type='checkbox';check.dataset.index=i;check.disabled=c.kind==='ambiguous';check.checked=c.kind!=='update'&&c.kind!=='ambiguous';label.append(check,el('span',' '+(c.label||c.newField?.label||c.record?.fields.find(f=>f.value)?.value||'新增经历')+'\n'+(c.reason||('现有：'+(c.oldValue||'空')+'\n导入：'+(c.patch?.value??c.newField?.value??'')))));host.append(label);} $('profile-apply').disabled=!changes.some(c=>c.kind!=='ambiguous');status(changes.length?`有 ${changes.length} 项待核对；未提供的旧信息不会删除，低精度日期不会覆盖完整日期。`:'没有需要更新的差异');}
$('profile-import').onchange=run(async()=>{const file=$('profile-import').files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('文件需小于 10MB');const incoming=ProfileCore.readWorkbook(XLSX,await file.arrayBuffer(),file.name);showDiff(ProfileCore.diff(profile,incoming));});
$('profile-apply').onclick=run(async()=>{let changes=[...$('profile-preview').querySelectorAll('input:checked')].map(n=>preview[Number(n.dataset.index)]);const ids=new Set(changes.filter(c=>c.addRecord).map(c=>c.recordId));if(changes.some(c=>c.newField&&!profile.records.some(r=>r.id===c.recordId)&&!ids.has(c.recordId)))throw Error('请同时勾选新增经历及其字段');await apply(changes);$('profile-preview').replaceChildren();$('profile-apply').disabled=true;});
$('profile-export').onclick=()=>download(ProfileCore.workbook(XLSX,profile),'EasyOffer个人资料库.xlsx');
$('profile-template').onclick=()=>download(ProfileCore.workbook(XLSX,ProfileCore.empty()),'EasyOffer空白资料模板.xlsx');
$('profile-undo').onclick=run(async()=>{const event=profile.history.findLast(h=>!h.undone);await rpc('undo',{operationId:event.operationId});await load();status('已撤销上次资料更新，保留其他后续编辑。');});
for(const type of ProfileCore.types){const option=el('option',ProfileCore.labels[type]);option.value=type;$('profile-type').append(option);}
$('profile-add').onclick=run(async()=>{const type=$('profile-type').value,id=crypto.randomUUID();const fields=({profile:[['name','中文姓名'],['phone','手机号码'],['email','常用邮箱']],education:[['school','学校名称'],['major','专业'],['degree','学历'],['start','开始日期'],['end','结束日期']],award:[['name','奖项名称'],['level','获奖等级'],['date','获奖日期'],['description','描述']],certificate:[['name','证书名称'],['date','获得日期'],['description','描述']],language:[['name','语种'],['level','熟练程度']],skill:[['name','技能'],['description','说明']],attachment:[['name','作品集名称'],['url','链接']]})[type]||[['name',type==='work'?'公司名称':'名称'],['role','角色'],['start','开始日期'],['end','结束日期'],['description','完整原始描述']];await apply([{recordId:id,addRecord:{type}},...fields.map(([key,label])=>({recordId:id,newField:{key:type==='work'&&key==='name'?'company':type==='education'&&key==='name'?'school':key,label,value:'',kind:['start','end','date'].includes(key)?'date':key==='description'?'longtext':'text'}}))]);});
// Retain the proven local file readers; only the confirmed diff writes the Profile.
$('profile-resume-file').onchange=run(async()=>{const file=$('profile-resume-file').files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('文件需小于 10MB');let text='';if(/\.pdf$/i.test(file.name)){const lib=await import('./vendor/pdf.mjs');lib.GlobalWorkerOptions.workerSrc=chrome.runtime.getURL('vendor/pdf.worker.mjs');const pdf=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;try{if(pdf.numPages>30)throw Error('请导入 30 页以内的简历');for(let i=1;i<=pdf.numPages;i++)text+=(await (await pdf.getPage(i)).getTextContent()).items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n';}finally{await pdf.destroy();}}else if(/\.docx$/i.test(file.name)){const zip=await JSZip.loadAsync(await file.arrayBuffer()),entry=zip.file('word/document.xml');if(!entry)throw Error('Word 文档无效');const raw=await entry.async('string');if(raw.length>5000000)throw Error('文件文字过长');const doc=new DOMParser().parseFromString(raw,'application/xml');text=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(n=>n.textContent).join('')).join('\n');}else text=await file.text();if(text.length>50000||text.trim().length<10)throw Error('请提供可读取的简历文字，扫描件需先转文字');$('profile-resume').value=text;status('文件已在本地读取，点击分析才会发送到配置的模型服务。');});
$('profile-analyze').onclick=run(async()=>{status('正在分析差异…');showDiff(await rpc('resume',{text:$('profile-resume').value}));});
$('profile-ai').onclick=run(async()=>{status('正在理解修改要求…');const result=await rpc('edit',{text:$('profile-instruction').value});if(result.ambiguous){status('目标不明确：'+result.reason);return;}showDiff(result.changes);status('已生成必要字段的修改，请核对后应用；替换原文不会额外润色。');});
// The old form is kept only for legacy script compatibility; it is never an editing entry.
for(const id of ['name','eduList','workList','projectList','campusList','customList','workbook-current'])$(id)?.closest('section')?.setAttribute('hidden','');
await load();
})().catch(error=>{document.getElementById('profile-status').textContent='资料加载失败：'+error.message;});
